import type { PhotoMeta } from './types'

/**
 * 손으로 쓰는 부분. 키는 `photos.generated.ts`의 `key`(= 원본 파일명)다.
 *
 * - `alt`는 스크린리더가 읽는다. 프레임에 실제로 무엇이 있는지 그대로 쓴다.
 * - `caption`은 설명이 아니라 시선이다. 사진이 이미 말한 걸 되풀이하지 않는다.
 * - `place`는 GPS 좌표에 붙이는 사람 이름표다. 좌표 자체는 EXIF에 있다.
 */
export const PHOTO_META: Readonly<Record<string, PhotoMeta>> = {
  // ── 강화 2022 ──────────────────────────────────────────
  '155262': {
    slug: 'modern-boot',
    title: 'Modern Boot',
    alt: 'A shop front of salvaged objects — sandals and boards hung on a stone wall beneath a balcony strung with bare bulbs.',
    caption: 'Everything on this wall used to be something else.',
    place: 'Ganghwa',
  },
  '155263': {
    slug: 'iron-garden',
    title: 'Iron Garden',
    alt: 'White wrought-iron chairs stand in an overgrown planter under a black steel staircase.',
    caption: 'Chairs left where the garden decided to grow.',
    place: 'Ganghwa',
  },

  // ── 간사이 2023 · 오사카 ────────────────────────────────
  'img-3220': {
    slug: 'two-lamps',
    title: 'Two Lamps',
    alt: 'Two red lantern-topped street lamps stand against a white plaster wall under a tangle of power lines.',
    caption: 'At attention, on a street with nobody on it.',
    place: 'Osaka',
  },
  'img-3221': {
    slug: 'okonomiyaki',
    title: 'Okonomiyaki',
    alt: 'Red paper lanterns and a menu board hang outside a wooden restaurant front.',
    caption: 'Lanterns lit before the first customer.',
    place: 'Osaka',
  },
  'img-3293': {
    slug: 'dotonbori',
    title: 'Dōtonbori',
    alt: 'Neon signs line both banks of a canal at dusk, their light doubled on the still water.',
    caption: 'The canal keeps a second city upside down.',
    place: 'Osaka',
  },

  // ── 간사이 2023 · 교토 ──────────────────────────────────
  'img-3575': {
    slug: 'kamo-at-noon',
    title: 'Kamo at Noon',
    alt: 'The Kamo river runs straight toward the horizon under a white sun, its walkways empty on both banks.',
    caption: 'Fourteen millimetres, and the river still refuses to bend.',
    place: 'Kyoto',
  },
  'img-3655': {
    slug: 'wooden-stage',
    title: 'Wooden Stage',
    alt: 'The wooden stage of Kiyomizu-dera stands on tall timber pillars above a bare winter hillside.',
    caption: 'The hillside drops away and the timber holds.',
    place: 'Kyoto',
  },
  'img-3746': {
    slug: 'vermilion-eaves',
    title: 'Vermilion Eaves',
    alt: 'A vermilion shrine gate with green copper eaves and a hanging lantern rises against a clear sky.',
    caption: 'Red against blue, with nothing in between.',
    place: 'Fushimi Inari',
  },
  'img-3777': {
    slug: 'thousand-gates',
    title: 'Thousand Gates',
    alt: 'A tunnel of vermilion torii recedes to a bright point, three people walking through it.',
    caption: 'The gates do the walking for you.',
    place: 'Fushimi Inari',
  },
  'img-4198': {
    slug: 'gates-after-dark',
    title: 'Gates After Dark',
    alt: 'Vermilion torii posts glow against black foliage at night, a single figure passing between them.',
    caption: 'The same gates with the daylight taken out.',
    place: 'Fushimi Inari',
  },

  // ── 간토 2025 · 아사쿠사·스미다 ─────────────────────────
  'img-5290': {
    slug: 'white-entrance',
    title: 'White Entrance',
    alt: 'A dark awning and a wall lamp mark the doorway of a plain white building.',
    caption: 'A door that gives nothing away.',
    place: 'Asakusa',
  },
  'img-5301': {
    slug: 'sticker-layer',
    title: 'Sticker Layer',
    alt: 'A utility cabinet is covered end to end in overlapping stickers beside a bare concrete pole.',
    caption: 'Years of it, one layer at a time.',
    place: 'Asakusa',
  },
  'img-5312': {
    slug: 'red-terrace',
    title: 'Red Terrace',
    alt: 'A row of red-painted shopfronts runs to a vanishing point beneath a web of power lines.',
    caption: 'One colour, held for a whole block.',
    place: 'Asakusa',
  },
  'img-5342': {
    slug: 'skytree-clear',
    title: 'Skytree, Clear',
    alt: 'The Skytree rises above a steel bridge and an elevated road under a cloudless sky.',
    caption: 'The tallest thing agrees to share the frame.',
    place: 'Sumida',
  },
  'img-5346': {
    slug: 'bridge-crossing',
    title: 'Bridge, Crossing',
    alt: 'A train crosses a white steel truss bridge over the river, a boat moored below.',
    caption: 'The bridge is busiest at eye level.',
    place: 'Sumida',
  },
  'img-5387': {
    slug: 'wire-spheres',
    title: 'Wire Spheres',
    alt: 'Gilded wire spheres sit along a riverside railing in front of an apartment block.',
    caption: 'Ornament with nothing to announce.',
    place: 'Sumida',
  },
  'img-5401': {
    slug: 'window-skytree',
    title: 'Window, Skytree',
    alt: 'A rounded water-bus window frames the Skytree and a gold-clad tower across the river.',
    caption: 'The boat decides what you get to see.',
    place: 'Sumida River',
  },
  'img-5406': {
    slug: 'the-helm',
    title: 'The Helm',
    alt: 'Inside a glass-roofed water bus, the pilot stands at the helm behind curved windows.',
    caption: 'Steel tubing, curved glass, and one person steering.',
    place: 'Sumida River',
  },
  'img-5446': {
    slug: 'dock-and-crane',
    title: 'Dock and Crane',
    alt: 'A white ship lies at a wharf below apartment towers, one still under construction with a crane on top.',
    caption: 'The skyline is never finished.',
    place: 'Tokyo Bay',
  },
  'img-5547': {
    slug: 'riverside-skytree',
    title: 'Riverside, Skytree',
    alt: 'A person leans against a riverside railing with the Skytree rising across the water behind them.',
    caption: 'The tower agrees to be a backdrop.',
    place: 'Sumida',
    // 편집을 거치며 EXIF가 통째로 지워진 프레임. 같은 날 같은 강변 컷들 사이에 놓는다.
    shotDate: '2025-01-09',
  },

  // ── 간토 2025 · 오다이바 ────────────────────────────────
  'img-5457': {
    slug: 'under-the-span',
    title: 'Under the Span',
    alt: 'The Rainbow Bridge sweeps overhead, its suspension cables fanning down toward the far shore.',
    caption: 'From underneath, a bridge is mostly geometry.',
    place: 'Odaiba',
  },
  'img-5479': {
    slug: 'silver-hull',
    title: 'Silver Hull',
    alt: 'A silver water bus with a domed glass roof waits at a pier beneath an elevated road.',
    caption: 'A boat drawn by someone who liked spaceships.',
    place: 'Odaiba',
  },
  'img-5492': {
    slug: 'daiba-station',
    title: 'Daiba Station',
    alt: 'Blue direction signs and a station nameplate hang from a pole beneath an elevated railway.',
    caption: 'Four instructions and one place name.',
    place: 'Odaiba',
  },
  'img-5496': {
    slug: 'no-parking-moon',
    title: 'No Parking, Moon',
    alt: 'A blue and red no-parking sign faces the sky, a pale half moon hanging just beyond it.',
    caption: 'The sign and the moon, the same size from here.',
    place: 'Odaiba',
  },
  'img-5509': {
    slug: 'red-man-waiting',
    title: 'Red Man Waiting',
    alt: 'A red pedestrian signal glows under an elevated deck above an empty paved walkway.',
    caption: 'Nobody to stop.',
    place: 'Odaiba',
  },
  'img-5510': {
    slug: 'overpass-stack',
    title: 'Overpass Stack',
    alt: 'Elevated roadways cross above a station entrance in the last light of the afternoon.',
    caption: 'Three levels of somewhere else.',
    place: 'Odaiba',
  },

  // ── 간토 2025 · 골목과 언덕 ─────────────────────────────
  'img-5556': {
    slug: 'twelve-to-eighteen',
    title: 'Twelve to Eighteen',
    alt: 'A blue pedestrian sign lists permitted hours beneath a knot of power lines and transformers.',
    caption: 'Even the sidewalk keeps a schedule.',
    place: 'Tokyo',
  },
  'img-5565': {
    slug: 'blue-stair',
    title: 'Blue Stair',
    alt: 'A blue steel staircase and railing climb the outside of a white building.',
    caption: 'One colour decides the whole facade.',
    place: 'Tokyo',
  },
  'img-5567': {
    slug: 'blue-passage',
    title: 'Blue Passage',
    alt: 'A narrow service passage under a blue roof runs between two buildings toward daylight.',
    caption: 'The gap the city forgot to fill.',
    place: 'Tokyo',
  },
  'img-5581': {
    slug: 'green-payphone',
    title: 'Green Payphone',
    alt: 'A green payphone sits in a metal booth against a tiled wall, direction signs above and below it.',
    caption: 'Still connected, probably.',
    place: 'Tokyo',
  },
  'img-5582': {
    slug: 'folding-bicycle',
    title: 'Folding Bicycle',
    alt: 'A teal folding bicycle stands on its kickstand against a grid of pale wall tiles.',
    caption: 'Parked like it was placed.',
    place: 'Tokyo',
  },
  'img-5585': {
    slug: 'old-charms',
    title: 'Old Charms',
    alt: 'A small red wooden box for spent shrine charms hangs on an iron fence among winter foliage.',
    caption: 'A box for things that have finished their job.',
    place: 'Tokyo',
  },
  'img-5586': {
    slug: 'two-crests',
    title: 'Two Crests',
    alt: 'Sunlight falls across wooden shrine doors marked with two dark crests, a rope and paper streamers above.',
    caption: 'Shut, and still the main event.',
    place: 'Tokyo',
  },
  'img-5588': {
    slug: 'green-bench',
    title: 'Green Bench',
    alt: 'Old illustrated books stand in a shop window above a weathered green bench.',
    caption: 'A bench for people who already bought something.',
    place: 'Tokyo',
  },
  'img-5592': {
    slug: 'counter-windows',
    title: 'Counter, Windows',
    alt: 'A long wooden counter and stools run beside a wall of windows in a white room.',
    caption: 'The room is mostly window.',
    place: 'Tokyo',
  },
  'img-5596': {
    slug: 'white-corridor',
    title: 'White Corridor',
    alt: 'A white corridor with a dark floor runs past a row of stools toward a lit room at the far end.',
    caption: 'A hallway that doubles as somewhere to sit.',
    place: 'Tokyo',
  },
  'img-5598': {
    slug: 'wooden-alley',
    title: 'Wooden Alley',
    alt: 'A paved alley runs between dark wooden houses toward a bright green tree.',
    caption: 'The tree is the only thing here that was not built.',
    place: 'Tokyo',
  },
  'img-5601': {
    slug: 'steps-and-gate',
    title: 'Steps and Gate',
    alt: 'Stone steps climb between plaster and timber walls to a dark wooden gate, pink flowers spilling over the wall above.',
    caption: 'Five steps and a decision.',
    place: 'Tokyo',
  },
  'img-5612': {
    slug: 'handrail-shadow',
    title: 'Handrail Shadow',
    alt: 'A red handrail throws a ladder of shadows across a paved slope below a concrete retaining wall.',
    caption: 'The shadow is a better drawing than the rail.',
    place: 'Tokyo',
  },
  'img-5621': {
    slug: 'poles-both-sides',
    title: 'Poles Both Sides',
    alt: 'Power poles line both sides of a narrow street running straight to a distant crossing.',
    caption: 'The wires arrive before the street does.',
    place: 'Tokyo',
  },
  'img-5622': {
    slug: 'kei-van',
    title: 'Kei Van',
    alt: 'A dark red kei van is parked against a concrete block retaining wall on a bright street.',
    caption: 'Small enough for the street it lives on.',
    place: 'Tokyo',
  },

  // ── 간토 2025 · 밤의 도쿄 ───────────────────────────────
  'img-5631': {
    slug: 'crossing-blurred',
    title: 'Crossing, Blurred',
    alt: 'A motorcyclist streaks across a crosswalk below stacked neon signs at night.',
    caption: 'The only things standing still are the buildings.',
    place: 'Shinjuku',
  },
  'img-5652': {
    slug: 'wooden-torii',
    title: 'Wooden Torii',
    alt: 'Visitors walk toward a tall wooden torii standing among winter trees.',
    caption: 'Everyone slows down at the gate.',
    place: 'Meiji Jingū',
  },
  'img-5653': {
    slug: 'bound-trunk',
    title: 'Bound Trunk',
    alt: 'A thick straw rope hung with folded paper streamers is tied around a broad tree trunk beside a shrine.',
    caption: 'The rope makes the tree a building.',
    place: 'Meiji Jingū',
  },
  'img-5659': {
    slug: 'takeshita-arch',
    title: 'Takeshita Arch',
    alt: 'Colourful padded shapes hang from the Takeshita Street arch above a large printed banner.',
    caption: 'The entrance shouts before the street does.',
    place: 'Harajuku',
  },
  'img-5667': {
    slug: 'blue-avenue',
    title: 'Blue Avenue',
    alt: 'Trees strung with blue lights arch over a road of moving traffic at night.',
    caption: 'Winter, wired for it.',
    place: 'Omotesandō',
  },
  'img-5674': {
    slug: 'tower-framed',
    title: 'Tower, Framed',
    alt: 'Tokyo Tower glows orange at night in a narrow gap between two dark buildings.',
    caption: 'The city leaves a slot for it.',
    place: 'Tokyo Tower',
  },
  'img-5688': {
    slug: 'night-slope',
    title: 'Night Slope',
    alt: 'A quiet street slopes downhill between lit apartment blocks at night.',
    caption: 'Late enough that the street belongs to nobody.',
    place: 'Roppongi',
  },
  'img-5690': {
    slug: 'roppongi-twice',
    title: 'Roppongi Twice',
    alt: 'The word Roppongi runs twice along an elevated walkway above a wet, reflecting deck.',
    caption: 'It says the name twice in case you missed it.',
    place: 'Roppongi',
  },

  // ── 간토 2025 · 하코네 가는 길 ──────────────────────────
  'img-5700': {
    slug: 'through-glass',
    title: 'Through Glass',
    alt: 'A commuter train waits beside a platform, seen through a window laced with overhead wires and signals.',
    caption: 'A layer of glass between you and the departure.',
    place: 'Tokyo',
  },
  'img-5706': {
    slug: 'romancecar',
    title: 'Romancecar',
    alt: 'The nose of a Romancecar bound for Hakone waits under a curved platform canopy.',
    caption: 'Named for the ride, not the destination.',
    place: 'Odawara',
  },
  'img-5707': {
    slug: 'exe-head-on',
    title: 'EXE, Head-On',
    alt: 'A Romancecar EXE stands head-on at the platform with its red marker lights lit.',
    caption: 'Symmetry, held for about a minute.',
    place: 'Odawara',
  },

  // ── 간토 2025 · 하코네 ──────────────────────────────────
  'img-5718': {
    slug: 'shrine-queue',
    title: 'Shrine Queue',
    alt: 'Visitors gather in front of vermilion shrine buildings beneath tall trees.',
    caption: 'Everyone waiting for the same thing.',
    place: 'Hakone',
  },
  'img-5727': {
    slug: 'through-the-cedars',
    title: 'Through the Cedars',
    alt: 'A vermilion torii stands in the lake, seen between tall cedar trunks over glittering water.',
    caption: 'The trees decide how much lake you get.',
    place: 'Lake Ashi',
  },
  'img-5743': {
    slug: 'one-boat',
    title: 'One Boat',
    alt: 'A single small boat sits on a lake of broken light below a dark forested ridge.',
    caption: 'Enough water to make one boat look deliberate.',
    place: 'Lake Ashi',
  },
  'img-5749': {
    slug: 'pirate-ship',
    title: 'Pirate Ship',
    alt: 'A replica galleon crosses the lake in front of forested mountains.',
    caption: 'A pirate ship on a crater lake, taken entirely seriously.',
    place: 'Lake Ashi',
  },
  'img-5780': {
    slug: 'ship-and-swans',
    title: 'Ship and Swans',
    alt: 'White swan pedal boats float in front of a moored galleon beneath a bare mountain.',
    caption: 'The fleet, at rest.',
    place: 'Lake Ashi',
  },
  'img-5805': {
    slug: 'parked-fuji',
    title: 'Parked, Fuji',
    alt: 'A silver hatchback is parked at a roadside with Mount Fuji rising beyond the ridge.',
    caption: 'The mountain turns up in the parking lot.',
    place: 'Hakone',
  },
  'img-5822': {
    slug: 'everyone-fuji',
    title: 'Everyone, Fuji',
    alt: 'A crowd stands along a roadside barrier looking toward Mount Fuji across a wide valley.',
    caption: 'The view arrives with an audience.',
    place: 'Hakone',
  },
  'img-5857': {
    slug: 'at-the-rail',
    title: 'At the Rail',
    alt: 'A person in a long coat stands at a barrier with Mount Fuji in the distance behind them.',
    caption: 'Standing where the photographer usually is not.',
    place: 'Hakone',
  },
  'img-5866': {
    slug: 'sulphur-vents',
    title: 'Sulphur Vents',
    alt: 'White steam pours from sulphur vents across a bare, rust-coloured volcanic slope.',
    caption: 'The mountain, still venting.',
    place: 'Ōwakudani',
  },

  // ── 간토 2025 · 요코하마 ────────────────────────────────
  'img-5886': {
    slug: 'promenade',
    title: 'Promenade',
    alt: 'A wide waterfront promenade runs toward the Minato Mirai skyline, a plane crossing the sky above.',
    caption: 'A path built to be walked slowly.',
    place: 'Yokohama',
  },
  'img-5890': {
    slug: 'hikawa-maru',
    title: 'Hikawa Maru',
    alt: 'The black and green hull of the Hikawa Maru lies moored along the quay.',
    caption: 'Retired, and still the biggest thing on the water.',
    place: 'Yokohama',
  },
  'img-5903': {
    slug: 'two-contrails',
    title: 'Two Contrails',
    alt: 'Two contrails cut diagonally across the sky above the tower of the prefectural office.',
    caption: 'The sky gets drawn on too.',
    place: 'Yokohama',
  },
  'img-5907': {
    slug: 'landmark-between',
    title: 'Landmark Between',
    alt: 'The Landmark Tower stands in the gap between a red brick building and a glass block.',
    caption: 'Old brick, new glass, and the tallest thing behind both.',
    place: 'Yokohama',
  },
  'img-5911': {
    slug: 'red-brick',
    title: 'Red Brick',
    alt: 'The long iron-balconied facade of the Red Brick Warehouse runs beside still water.',
    caption: 'A warehouse that outlived its cargo.',
    place: 'Yokohama',
  },
  'img-5914': {
    slug: 'cosmo-clock-1449',
    title: 'Cosmo Clock, 14:49',
    alt: 'The Cosmo Clock ferris wheel reads 14:49 above the buildings of Minato Mirai.',
    caption: 'A ferris wheel that is also the town clock.',
    place: 'Yokohama',
  },
  'img-5920': {
    slug: 'cosmo-clock-2150',
    title: 'Cosmo Clock, 21:50',
    alt: 'The same ferris wheel glows pink and violet against a black sky, reading 21:50.',
    caption: 'Seven hours on, the clock is the only thing still lit.',
    place: 'Yokohama',
  },
}
